### PR TITLE
Added custom_session_id handling

### PR DESCRIPTION
**Pull request by frogermcs**
Add the ability to define custom_session_id for the conversation with bot.

### CODE REVIEW

**Comment by frogermcs** [comment]
I signed it!

**Comment by frogermcs** [comment]
For some reason my integration with chatbase logs sessions longer than 1h what looks impossible for voice assistant with scenario shorter than 3 messages. Adding custom_session_id could help with handling session length on chatbot side.

Mentioned integration was implemented in https://github.com/frogermcs/WaterLog-assistant-app (Google Assistant + Dialogflow).

**Comment by lorenzbaum** [comment]
What's the problem? Just merge this feature, as we all need it!

**Comment by frogermcs** [comment]
And the second side of this improvement: https://github.com/actions-on-google/actions-on-google-nodejs/pull/90 :)

**Comment by cristiancavalli** [comment]
@frogermcs Thanks!

**Comment by lorenzbaum** [comment]
How about releasing it on npm?

**Comment by writtmeyer** [comment]
@cristiancavalli Please update the minor version of it and publish it to npm. It's and important addition we all would love to see :-)

**Pull request merged**
